Update Mauth call with retryattempts=5 and added pause_cap =1800 for PUT request.
mdsol/RMauthClient pull request #13
Opened 2021-02-22 06:44 UTC by sjigali-df-mdsol

2021-02-23 15:19 UTC, jprice-mdsol requested changes

2021-02-23 15:19 UTC, jprice-mdsol commented on R/RMauthClient.R
> +    RETRY(verb = "PUT", url = requestURL, config = add_headers(.headers = mAuthHeader), body=body, ause_cap=pause_cap, times = retryAttempts)
Typo `ause_cap`

2021-02-24 04:44 UTC, sjigali-df-mdsol commented on R/RMauthClient.R
> +    RETRY(verb = "PUT", url = requestURL, config = add_headers(.headers = mAuthHeader), body=body, ause_cap=pause_cap, times = retryAttempts)
I have updated

2021-02-24 04:49 UTC, jprice-mdsol approved these changes

2021-02-24 04:49 UTC, merged